name: data516
channels:
  - defaults
dependencies:
  - pip=23.3
  - python=3.10
  - jupyter=1
  - notebook=6
  - pandas=1.5
  - numpy-base=1.23.5
  - matplotlib=3.5.3
  - pip:
      - IMDbPY==6.0
      - psycopg2==2.9.9
      - pyspark
